from enum import StrEnum


class CoreState(StrEnum):
    IDLE = "IDLE"
    BLOCKED = "BLOCKED"
    CONTEXT_OK = "CONTEXT_OK"
    ARMED = "ARMED"
    ENTRY_PENDING = "ENTRY_PENDING"
    PROTECTING = "PROTECTING"
    VALIDATING = "VALIDATING"
    PROTECTED = "PROTECTED"
    TARGET_EXIT_PENDING = "TARGET_EXIT_PENDING"
    EXIT_PENDING = "EXIT_PENDING"
    RECONCILING = "RECONCILING"
    RECOVERING = "RECOVERING"
    COOLDOWN = "COOLDOWN"
    LOCKED = "LOCKED"
    EMERGENCY_EXIT = "EMERGENCY_EXIT"


class ReconcilePhase(StrEnum):
    NONE = "NONE"
    ZERO_QTY_CONFIRMATION = "ZERO_QTY_CONFIRMATION"
    RESIDUAL_ORDER_CLEANUP = "RESIDUAL_ORDER_CLEANUP"
    FINAL_FLAT_CONFIRMATION = "FINAL_FLAT_CONFIRMATION"


class ExitDecision(StrEnum):
    HOLD = "HOLD"
    EXIT_TARGET = "EXIT_TARGET"
    EXIT_PROTECTION = "EXIT_PROTECTION"
    EXIT_TIME = "EXIT_TIME"
    EXIT_STRUCTURE = "EXIT_STRUCTURE"
    EXIT_EMERGENCY = "EXIT_EMERGENCY"


class IncidentLevel(StrEnum):
    P0 = "P0"
    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
